In [1]:
import json
import math
import numpy as np
import pandas as pd
import datetime

In [2]:
data = pd.read_excel('../data/raw/raw_data.xlsx')

In [3]:
data.sort_values(by='id').head()

,id,name(название),specialization(специализация),responsibilities(Должностные обязанности),requirements(Требования к соискателю),terms(Условия),skills(Ключевые навыки),salary_from,salary_to,object,...,updated_by,position,phone,website,email,image,unique_code,city_code,source_id,link_resource
3,2,Арматурщик,Арматурщик,Выполнение работ по гнутью и резке арматурной ...,Выполнение работ по гнутью и резке арматурной ...,NaN,\N,50000,100000,"ООО ""АЛЬМИС_ИНТЕГРАЛ""",...,1,Арматурщик,74959214241,https://almisintegral.ru/,info@almisintegral.ru,\N,\N,\N,1,\N
70,12933,Сварщик,\N,Выполнение качественной сварки в различных про...,Действующее аттестационное удостоверение по со...,"Работа на строительных объектах в г.Пушкин, по...",NaN,60000,\N,NaN,...,529,NaN,+8 (812) 870-50-20,NaN,hr@kvsspb.ru,\N,V-78-00012933,\N,1,https://spb.hh.ru/vacancy/53945969?hhtmFrom=em...
23,13376,Монтажник,\N,Требуются БЕТОНЩИКИ /АРМАТУРЩИКИ и рабочие спе...,"знать устройство трактора, принципы его работы...","Проживание, 2-ухразовое питание._x000D_\nОформ...",NaN,45000,90000,Барклая,...,767,Монтажник С и ЖБК,+8 (925) 760-10-44,NaN,v.seli@mail.ru,62344f70903c4.jpg,V-77-00013376,\N,1,NaN
22,13387,сварщик,\N,Обязанности:\n• Подготовка к сварочным работам...,Удостоверение сварщика или запись в трудовой к...,Питание/Проживание.\nОформление по ТК РФ\nВыпл...,NaN,45000,90000,"СДКП, Северный дублер Кутузовского проспекта",...,767,сварщик,+8 (925) 760-10-44,NaN,v.seli@mail.ru,623453d3947a7.jpg,V-77-00013387,\N,1,NaN
73,13674,Строительная бригада,\N,"строительство ЖК ""Смарт СИТИ"" п. Новинки_x000D...","опыт работы от 1 года,_x000D_\nработоспособнос...","Оплата труда высокая, согласно выполненных раб...","Работоспособность, знание современных технолог...",40000,\N,Жилой комплекс СМАРТ СИТИ,...,808,NaN,+7 (495) 137-70-62,polytechstroy.ru,n.zavalnyk@polytechstroy.ru,62385253c5767.jpg,V-52-00013674,\N,1,https://hh.ru/vacancy/49720831?hhtmFrom=employ...

In [4]:
data.columns

Index(['id', 'name(название)', 'specialization(специализация)',
       'responsibilities(Должностные обязанности)',
       'requirements(Требования к соискателю)', 'terms(Условия)',
       'skills(Ключевые навыки)', 'salary_from', 'salary_to', 'object', 'city',
       'address', 'type_of_employment_id(Тип занятости)',
       'expirience(опыт работы)', 'langs(знание языков)', 'rights_id',
       'notes(Примечания)', 'employer_id', 'status_id', 'status_date',
       'dadata_object', 'type_job_id(Вид работы)', 'speciality_id',
       'work_experience_id', 'created_by', 'updated_by', 'position', 'phone',
       'website', 'email', 'image', 'unique_code', 'city_code', 'source_id',
       'link_resource'],
      dtype='object')

In [5]:
data_small = data[['id', 'responsibilities(Должностные обязанности)', 'requirements(Требования к соискателю)', 'terms(Условия)', 'notes(Примечания)']]

In [6]:
data_small = data_small.fillna(value='')

In [7]:
data_small.head()

,id,responsibilities(Должностные обязанности),requirements(Требования к соискателю),terms(Условия),notes(Примечания)
0,9495846,Работа на строительных площадках. Очистных соо...,,,Работа на строительных площадках. Очистных соо...
1,9495850,Гнутье арматурной стали на механических станка...,,,
2,9495851,Вязка арматуры.,,,
3,2,Выполнение работ по гнутью и резке арматурной ...,Выполнение работ по гнутью и резке арматурной ...,,\N
4,9388857,Вахта в город Москва. Обязанности: - армирова...,опыт в строительстве приветствуется; работа в ...,продолжительность вахты 60/30 (продление вахты...,Официальное трудоустройство; - ЗП в срок и без...

In [8]:
data_small.loc[data_small[data_small['notes(Примечания)'] == '\\N'].index, 'notes(Примечания)'] = ''

In [9]:
data_small.dtypes

id                                            int64
responsibilities(Должностные обязанности)    object
requirements(Требования к соискателю)        object
terms(Условия)                               object
notes(Примечания)                            object
dtype: object

In [10]:
def parse_indexes(big_sent, small_sent):
    if len(small_sent) != 0 and small_sent in big_sent:
        start_ind = big_sent.index(small_sent)
        return (start_ind, start_ind + len(small_sent))
    return -1

In [11]:
data_small.head()

,id,responsibilities(Должностные обязанности),requirements(Требования к соискателю),terms(Условия),notes(Примечания)
0,9495846,Работа на строительных площадках. Очистных соо...,,,Работа на строительных площадках. Очистных соо...
1,9495850,Гнутье арматурной стали на механических станка...,,,
2,9495851,Вязка арматуры.,,,
3,2,Выполнение работ по гнутью и резке арматурной ...,Выполнение работ по гнутью и резке арматурной ...,,
4,9388857,Вахта в город Москва. Обязанности: - армирова...,опыт в строительстве приветствуется; работа в ...,продолжительность вахты 60/30 (продление вахты...,Официальное трудоустройство; - ЗП в срок и без...

In [12]:
data_small.loc[data_small[data_small['id'] == 9492540].index, 'terms(Условия)'] = '5/2'

In [13]:
for n, col in enumerate(data_small.columns[1:]):
    data_small[f'{col}_extracted_indexes'] = data_small.apply(lambda row: parse_indexes(row['responsibilities(Должностные обязанности)'], row[col]), axis=1)

In [18]:
data_small.head()

,id,responsibilities(Должностные обязанности),requirements(Требования к соискателю),terms(Условия),notes(Примечания),responsibilities(Должностные обязанности)_extracted_indexes,requirements(Требования к соискателю)_extracted_indexes,terms(Условия)_extracted_indexes,notes(Примечания)_extracted_indexes
0,9495846,Работа на строительных площадках. Очистных соо...,,,Работа на строительных площадках. Очистных соо...,"(0, 55)",-1,-1,"(0, 55)"
1,9495850,Гнутье арматурной стали на механических станка...,,,,"(0, 140)",-1,-1,-1
2,9495851,Вязка арматуры.,,,,"(0, 15)",-1,-1,-1
3,2,Выполнение работ по гнутью и резке арматурной ...,Выполнение работ по гнутью и резке арматурной ...,,,"(0, 190)","(0, 106)",-1,-1
4,9388857,Вахта в город Москва. Обязанности: - армирова...,опыт в строительстве приветствуется; работа в ...,продолжительность вахты 60/30 (продление вахты...,Официальное трудоустройство; - ЗП в срок и без...,"(0, 621)",-1,"(143, 199)","(203, 621)"

In [17]:
data_json = []

In [19]:
for index, row in data_small.iterrows():
    if row['requirements(Требования к соискателю)_extracted_indexes'] != -1:
        req_start, req_end = row['requirements(Требования к соискателю)_extracted_indexes']
    else:
        req_start, req_end = -1, -1

    if row['terms(Условия)_extracted_indexes'] != -1:
        ter_start, ter_end = row['terms(Условия)_extracted_indexes'] 
    else:
        ter_start, ter_end = -1, -1

    if row['notes(Примечания)_extracted_indexes'] != -1:
        notes_start, notes_end = row['notes(Примечания)_extracted_indexes']
    else:
        notes_start, notes_end = -1, -1
    
    data_json.append({
        'id': row['id'],
        'text': row['responsibilities(Должностные обязанности)'],
        'extracted_part': {
            'requirements': {
                'start_index': req_start,
                'end_index': req_end,
                'text' : row['requirements(Требования к соискателю)'],
            },
            'terms': {
                'start_index': ter_start,
                'end_index': ter_end,
                'text': row['terms(Условия)'],
            },
            'notes': {
                'start_index': notes_start,
                'end_index': notes_end,
                'text': row['notes(Примечания)'],
            }
        }
    })

In [22]:
with open("data.json", "w") as final:
   json.dump(data_json, final, indent=4)